"""init

Revision ID: a69f5f1dd689
Revises: 
Create Date: 2022-11-13 14:24:04.821286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a69f5f1dd689'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_artefacts',
                    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'),
                              nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('user_id', sa.String(length=512), nullable=False),
                    sa.Column('is_destroyed', sa.Boolean(), nullable=True),
                    sa.Column('session_token', sa.String(length=2048), nullable=False),
                    sa.Column('access_token', sa.String(length=2048), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('access_token'),
                    sa.UniqueConstraint('session_token')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authorization_artefacts')
    # ### end Alembic commands ###
